FROM openjdk:21-jdk

WORKDIR /app

COPY target/restaurant-ms-0.0.1-SNAPSHOT.jar restaurant-ms-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENV DATABASE_URL=${DATABASE_URL}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV AWS_ACCESS_ID=${AWS_ACCESS_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV CLOUDFLARE_R2_ENDPOINT=${CLOUDFLARE_R2_ENDPOINT}

ENTRYPOINT ["java", "-jar", "restaurant-ms-0.0.1-SNAPSHOT.jar"]