FROM openjdk:21-jdk

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENV DATABASE_URL=${DATABASE_URL}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV AWS_ACCESS_ID=${AWS_ACCESS_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV CLOUDFLARE_R2_ENDPOINT=${CLOUDFLARE_R2_ENDPOINT}

ENTRYPOINT ["java", "-jar", "app.jar"]