version: "3.8"

services:
  pg-prisma:
    image: bitnami/postgresql:latest
    container_name: restaurant-db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=restaurantdb
      - DATABASE_URL=jdbc:postgresql://localhost:5433/restaurantdb
