name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Build with maven'
        run: mvn clean install -DskipTests

      - name: "list target"
        run: ls

      - name: 'Generate tag'
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: 'Login into the container registry'
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: 'Build and Push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thiago0503/restaurant-ms:${{steps.generate_tag.outputs.sha}}, thiago0503/restaurant-ms:latest

  deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull image docker hub
          run: docker pull thiago0503/restaurant-ms:latest
        - name: remove container
          run: docker rm -f restaurant-ms
        - name: Run docker container
          run: docker run -d -p 8080:8080 -e CLOUDFLARE_R2_ENDPOINT=${{secrets.CLOUDFLARE_R2_ENDPOINT}} -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} -e AWS_ACCESS_ID=${{secrets.AWS_ACCESS_ID}} -e DATABASE_URL=${{secrets.DATABASE_URL}} --name restaurant-ms thiago0503/restaurant-ms:latest
